<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>2.0.1.0</Version>
        <AssemblyVersion>2.0.1.0</AssemblyVersion>
        <FileVersion>2.0.1.0</FileVersion>
        <InformationalVersion>2.0.1.0</InformationalVersion>
        <PackageProjectUrl>https://github.com/ArcaneAj/WachuMakeyMaking</PackageProjectUrl>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
        <TargetFramework>net10.0-windows</TargetFramework>
        <PlatformTarget>x64</PlatformTarget>

        <NoWarn>$(NoWarn);IDE0063</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.12" />
    </ItemGroup>
</Project>
